# 1. CONFIGURA\u00c7\u00d5ES DO SERVIDOR
server.port=8080
spring.application.name=notepad-backend

# 2. CONFIGURAÇOES DO BANCO DE DADOS (SUPABASE - POSTGRESQL)
spring.datasource.url=jdbc:postgresql://db.uruhnfcchfvtxknbbbae.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=trindadeUEG
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. CONFIGURAÇOES DO JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

